/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: '#111417',
        'surface-dim': '#111417',
        'surface-bright': '#37393d',
        'surface-container-lowest': '#0c0e12',
        'surface-container-low': '#191c1f',
        'surface-container': '#1d2023',
        'surface-container-high': '#282a2e',
        'surface-container-highest': '#323539',
        'on-surface': '#e1e2e7',
        'on-surface-variant': '#cbc3d7',
        'inverse-surface': '#e1e2e7',
        'inverse-on-surface': '#2e3134',
        outline: '#958ea0',
        'outline-variant': '#494454',
        'surface-tint': '#d0bcff',
        primary: '#d0bcff',
        'on-primary': '#3c0091',
        'primary-container': '#a078ff',
        'on-primary-container': '#340080',
        'inverse-primary': '#6d3bd7',
        secondary: '#4edea3',
        'on-secondary': '#003824',
        'secondary-container': '#00a572',
        'on-secondary-container': '#00311f',
        tertiary: '#ffb2b7',
        'on-tertiary': '#67001b',
        'tertiary-container': '#ff516a',
        'on-tertiary-container': '#5b0017',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#e9ddff',
        'primary-fixed-dim': '#d0bcff',
        'on-primary-fixed': '#23005c',
        'on-primary-fixed-variant': '#5516be',
        'secondary-fixed': '#6ffbbe',
        'secondary-fixed-dim': '#4edea3',
        'on-secondary-fixed': '#002113',
        'on-secondary-fixed-variant': '#005236',
        'tertiary-fixed': '#ffdadb',
        'tertiary-fixed-dim': '#ffb2b7',
        'on-tertiary-fixed': '#40000d',
        'on-tertiary-fixed-variant': '#92002a',
        background: '#111417',
        'on-background': '#e1e2e7',
        'surface-variant': '#323539',
      },
      fontFamily: {
        playfair: ['"Playfair Display"', 'serif'],
        jakarta: ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      borderRadius: {
        'sm': '0.5rem',
        DEFAULT: '1rem',
        'md': '1.5rem',
        'lg': '2rem',
        'xl': '3rem',
        'full': '9999px',
      },
      spacing: {
        base: '8px',
        gutter: '24px',
        'margin-mobile': '16px',
        'margin-desktop': '64px',
        'max-width': '1200px',
      },
      boxShadow: {
        'neon': '0 0 20px -5px rgba(208, 188, 255, 0.4)',
        'neon-hover': '0 0 30px -5px rgba(208, 188, 255, 0.6)',
      }
    },
  },
  plugins: [],
}
